packages:
  - examples/*

catalog:
  '@js-temporal/polyfill': ^0.5.1
  temporal-polyfill: ^0.3.0
  temporal-polyfill-lite: ^0.2.0
  typescript: 5.9.3
  vite: ^7.2.7

onlyBuiltDependencies:
  - esbuild
