packages:
  - examples/*

catalog:
  '@js-temporal/polyfill': ^0.5.1
  temporal-polyfill: ^1.0.1
  temporal-polyfill-lite: ^0.4.0
  typescript: 6.0.3
  vite: 8.0.16

minimumReleaseAgeExclude:
  - temporal-polyfill-lite
